### ISSUE TITLE
Meta Integration

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#251]
```[tasklist]
### Desiderata
- [x] Have someone read a coherent draft
- [x] Preview link
- [x] Keywords/tags
- [x] Title image
- [x] Link preview excerpt
- [x] New image for the True Self draft
- [x] Published at https://blog.beeminder.com/metamind/ on 2022-12-30
- [x] Blog blurbs
- [x] Tweet
- [x] Tip of the day
```

## Cognata

* #48 

_**Verbata**: autodata integrations, metaminder, metamind, metaminding,_
