### ISSUE TITLE
The Checks & Balances Protocol for Bug Tracking

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#303]
```[tasklist]
### Desiderata
- [ ] Have someone read a draft
- [ ] Secretpreview link
- [ ] Keywords/tags
- [ ] Title image
- [ ] Link preview excerpt
- [ ] Publish
- [ ] Blog blurbs
- [ ] Waggledance
- [ ] Tweet
- [ ] Tip of the day
```

Joel Spolsky in his classic post on [Painless Bug Tracking](https://www.joelonsoftware.com/2000/11/08/painless-bug-tracking/ "This thing is going on a quarter century old and was originally kind of an advertisement for FogBugz"):

> When a bug is resolved, it gets assigned back to the person who opened it. This is a crucial point. It does _not_ go away just because a programmer thinks it should. The golden rule is that only the person who opened the bug can close the bug. The programmer can _resolve_ the bug, meaning, “hey, I think this is done,” but to actually _close_ the bug and get it off the books, the original person who opened it needs to confirm that it was actually fixed or agree that it shouldn’t be fixed for some reason.

AKA "opener closers". Here's what that evolved into in Beeminderland:

## The check&balances protocol for closing&resolving gissues

Every closed gissue should get a label for why it was closed (fixed, nixed, duplicate, could-not-replicate, etc). However, to make sure the person who opened the gissue agrees and signs off on the resolution, the person resolving the gissue should _either_ close it or add the resolution label but not _both_. Nudge the opener of the gissue to resolve if you closed it or close it if you resolved it. See the Quick Links in the README for closed-but-unresolved gissues.

## Cognata

* #195 

_**Verbata**: software engineering principles, gissue management, spolsky,_

**Comment by dreeves** [comment]
FAQ: What if I create a gissue myself and then resolve it myself?

Then you're good. You can both resolve and close. "Opener closes".

**Comment by dreeves** [comment]
TODO: me elsewhere: "meta: avoid both closing and resolving unless it's your own gissue. Which this one technically was but then got assigned to other people"
