### ISSUE TITLE
Meta-gissue: Blog ideas collected by Mary

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#36]
- [ ] Point/counterpoint on never-ending goals vs. time-bound goals
- [ ] Counterpoint post to Paying Is Not Punishment
- [ ] shanaqui: Do we have any kind of goal-setting FAQs? Someone's asking "how do I set up a goal about reducing a habit and if we do not have an FAQ about it somewhere, I'm tempted to suggest I do a blog post about goal setting with a bunch of common examples, to be pointed at whenever people ask this kind of question.
- [ ] shanaqui: Yeah! Actually, a guest blog by Adam (or me-and-Adam, or just me if Adam prefers, or you if you prefer) about the joys of beeminding beemergencies would actually possibly be really good, if doing it via IFTTT works.
- [ ] adam: Do we have any blog posts about "thinking about what you'll do if your safety buffer gets low"? i.e. plan how you can "do the thing" I think that's a critical aspect of goal creation at beeminder, and I think maybe we have glossed over it? If we were better set up for experiments I'd like to either have users enter in a box that says "In order to achieve this goal, the actions I will take are: ___" either in goal creation or a few days later via email...
- [ ] Forum post or draft guest blog post about ambitiousness and lots of fine print vs caution and very bright lines
