### ISSUE TITLE
Hyperrational Goal Tracking

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#454]
```[tasklist]
### Desiderata
- [ ] Have someone read a draft
- [ ] Secretpreview link
- [ ] Keywords/tags
- [ ] Title image
- [ ] Link preview excerpt
- [ ] Publish
- [ ] Blog blurbs
- [ ] Waggledance
- [ ] Tweet
- [ ] Tip of the day
```

question from the internet: what do we mean by calling Beeminder hyperrational goal tracking?

Before I give my answer, and to show that "hyperrational" isn't pure neologism, here's the inventor of Ruby on Rails using it in the context of sociopathic companies (a favorite topic of mine as well -- see [blog.bmndr.co/psychpricing](http://blog.bmndr.co/psychpricing) and [blog.bmndr.co/burglebug](http://blog.bmndr.co/burglebug) for example):

> [Fines on tech companies] put a price on
> criminal behavior, and if the gains from
> committing those crimes exceed the cost
> of the fines, there's a base hyper-rational
> calculus that says the company should
> continue to break the law.

So hyperrational means excessively rational, in some sense, and I'm kind of making fun of ourselves by applying it to Beeminder. But also it's because Beeminder in a sense fights irrationality with irrationality. Homo economicus would never opt in to a commitment device except for a strategic game-theoretic reason involving other players. A perfectly rational person is perfectly cooperative with *themself*. A commit device needlessly constrains your future actions. Sacrificing optionality is costly! But for humans suffering from hyperbolic discounting, it elegantly corrects for a different irrationality and leaves you more rational.

I liked how Bee put it: It's so rational it's irrational again. She also mentioned fighting irrationality with irrationality. (Yes, I gave her $5 of credit too.)

GPT-4 was probably among the best responses and probably would've gotten $5 if it were a Beeminder user:

> In the context of Beeminder it refers to a
> highly logical and systematic approach to
> setting, tracking, and achieving personal
> goals. [lots more cogent stuff about
> Beeminder] The prefix "hyper" is used to
> emphasize the extreme or excessive
> nature of the rationality involved [blah
> blah blah] stand out from other tools and
> methods that may not be as rigorous or
> systematic in their approach.

Ok, enough of all that. I was worried that some people might find it obnoxiously obtuse or pretentious but I see it's one of the favorite taglines in the collection:

https://beeminder.consider.it/#whats-the-best-beeminder-tagline-11

(Feel free to add your opinions there!)

## Cognata

* https://beeminder.consider.it/#whats-the-best-beeminder-tagline-11

_**Verbata**: beeminder philosophy, hyper-rational goal tracking, rationality,_

**Comment by dreeves** [comment]
Original beemail from 2023-04-11:

daily beemail: what does "hyperrational goal tracking" mean?

Question from the internet. One of Beeminder's first taglines, still in rotation on the front page, is "Hyperrational goal tracking". What does that mean?

STRAW POLL: What do *you* think it means?

Best answer gets $5 of premium credit. I've written down my own answer which I'll show you in the next beemail.

[next day]

Thanks for all the replies about hyperrationality! I don't want to play favorites so I'm giving $5 of credit to everyone who gave an answer that in some way distinguished from just meta-rationality. (And apologies to lifetime premium people for whom there's no such thing as premium credit -- maybe someday we'll have derail credit! "Honey money", I want to call it. But that's a can of worms for another day.)

**Comment by dreeves** [comment]
Maybe I could also find an excuse to quote this quintessence of (the good kind of) hyperrationality from Eliezer Yudkowsky:

> Let me try to clear up the notion that economically rational agents must be cold, heartless creatures who put a money price on everything.
>
> There doesn't have to be a financial price you'd accept to kill every sentient being on Earth except you. There doesn't even have to be a price you'd accept to kill your spouse. It's allowed to be the case that there are limits to the total utility you know how to generate by spending currency, and for anything more valuable to you than that, you won't exchange it for a trillion dollars.
> 
> Now, it *does* have to be the case for a von Neumann-Morgenstern rational agent that if a sum of money has any value to you at all, you will exchange anything else you have -- or any possible event you can bring about -- *at some probability* for that sum of money. So it *is* true that as a rational agent, there is some *probability* of killing your spouse, yourself, or the entire human species that you will cheerfully exchange for $50.
>
> I hope that clears up exactly what sort of heartless creatures economically rational agents are.

**Comment by dreeves** [comment]
![tmpa](https://github.com/user-attachments/assets/b888ae86-0f80-4e6f-a2f7-a51fe823d19f)
